version: '3.0'

services:

  client:
    image: nginx
    container_name: nginx
    ports:
      - 80:5173
    networks:
      - client_connected_services
      - exposed
    depends_on:
      - server
      - ws
  
  server:
    image: ./server
    container_name: server
    hostname: server
    ports:
      - 8080
    networks:
      - db_connected_services
      - client_connected_services
    depends_on:
      - mariadb
    
  ws:
    image: ./ws
    container_name: ws
    hostname: ws
    ports:
      - 8081
    networks:
      - client_connected_services
      - db_connected_services
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: mariadb
    ports: 
      - 3036
    networks:
      - db_connected_services
    volumes:
      - mariadb-volume:/data

volumes:
  mariadb-volume: {}

networks:
  db_connected_services:
    name: db_connected_services
    internal: true
  client_connected_services:
    name: client_connected_services
    internal: true
  exposed:
    name: exposed