name: build-server

on:
    push:
        tags:
            - v*

jobs:
    build-job:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Installing & building
            run: |
              cd server
              npm install
              npm run build --if-present
              cp -r node_modules build

          - name: Archive production (server) artifacts
            uses: actions/upload-artifact@v4
            with:
              name: server
              path: ./server/build
