name: build-ws

on:
  push:
      tags:
          - v*

jobs:
    build-job:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: npm install, build, and test
            run: |
              cd ws
              npm install
              npm run build --if-present
              cd build
              npm install --omit=dev

          - name: Archive production (ws) artifacts
            uses: actions/upload-artifact@v4
            with:
              name: ws
              path: ./ws/build
