name: workflow

on:
  push:
      tags:
          - v*

jobs:
  #test-backend:
  #  name: Test-Backend
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout repository
  #      uses: actions/checkout@v4
  #    - name: Testing
  #      run: |
  #        cd backend
  #        npm install
  #        npm run test

  build-client:
    name: Build-Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Installing packages
        run: npm install
        working-directory: ./client
      - name: Building
        run: npm run build --if-present
        working-directory: ./client
      - name: Archive production client artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-build-${{ github.ref_name }}
          path: ./client/dist
    #needs: [test-backend]

  build-backend:
    name: Build-Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install packages
        run: npm install
        working-directory: ./backend
      - name: Building
        run: npm run build --if-present
        working-directory: ./backend
      - name: Archive production backend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-${{ github.ref_name }}
          path: ./backend/dist
  
  build-ws:
    name: Build-WS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install packages
        run: npm install
        working-directory: ./ws
      - name: Building
        run: npm run build --if-present
        working-directory: ./ws
      - name: Archive production ws artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ws-build-${{ github.ref_name }}
          path: ./ws/dist

  build-and-push-images:
    name: Docker-Build-Push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Download backend build
        uses: actions/download-artifact@v4
        with:
          path: ./backend
          name: backend-build-${{ github.ref_name }}
      - name: Unzip backend build
        run: ls && unzip backend-build-${{ github.ref_name }}.zip
        working-directory: ./backend
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: therayquaza/loqui_chat:backend-${{ github.ref_name }}

      - name: Download client build
        uses: actions/download-artifact@v4
        with:
          path: ./client
          name: client-build-${{ github.ref_name }}
      - name: Unzip client build
        run: unzip client-build-${{ github.ref_name }}.zip
        working-directory: ./client
      - name: Build and push client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: therayquaza/loqui_chat:client-${{ github.ref_name }}
      
      - name: Download ws build
        uses: actions/download-artifact@v4
        with:
          path: ./ws/dist
          name: ws-build-${{ github.ref_name }}
      - name: Unzip ws build
        run: unzip ws-build-${{ github.ref_name }}.zip
        working-directory: ./ws
      - name: Build and push ws
        uses: docker/build-push-action@v6
        with:
          context: ./ws
          push: true
          tags: therayquaza/loqui_chat:ws-${{ github.ref_name }}
    needs: [build-ws, build-backend, build-client]